server:
  port: 8888
  servlet:
    context-path: /xxx

mybatis:
  # 注册映射文件
  mapper-locations: classpath:com/abc/dao/*.xml
  # 注册实体类别名
  type-aliases-package: com.abc.bean

# 注册数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 111
